networks:
  backend-cardin:

volumes:
  sqlserver-volume:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=CardinTiako#2023
      - ACCEPT_EULA=Y
    ports:
      - "5431:1433"
    volumes:
      - sqlserver-volume:/var/opt/mssql
    networks:
      - backend-cardin

  # backendservice:
  #   restart: always
  #   image: cardin21/backendservice:latest
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #   networks:
  #     - backend-cardin
  #   depends_on:
  #     - rabbitmq
  #     - sqldata
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://0.0.0.0:80
  #   ports:
  #     - "5020:80"